name: Build and cache

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@v3

      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Build default package
        run: nix build --print-build-logs .#default
